export let products = [
  {
    id: 1,
    title: "Calza Corta Renata",
    price: 14000,
    stock: 3,
    description: "Calza corta de lycra, sublimada",
    description2: "Calza corta de Lycra de primera calidad (92% poliester y 8% elastómero).    Estampada mediante sublimacion. Resistente a la exposición al sol, cloro y agua. Faja de 8cm.    Elastico de 0,5 cm en la faja. Costuras reforzadas. RECOMENDACION DE TALLES: TALLE 1: 34/36/38 pantalón TALLE 2: 38/40/42 pantalón- REFERENCIA: La modelo de la foto esta usando un TALLE 1. *Las medidas pueden variar en milímetros debido a la confección, tipo de tela y costuras.",
    category: "calzascortas",
    img: "https://res.cloudinary.com/dxzytrwpw/image/upload/v1712944144/IMG_4845_a6an8e.jpg",
  },

  {
    id: 2,
    title: "Calza Corta Sara",
    price: 14000,
    stock: 3,
    description: "Calza corta de lycra, sublimada",
    description2: "Calza corta de Lycra de primera calidad (92% poliester y 8% elastómero).    Estampada mediante sublimacion. Resistente a la exposición al sol, cloro y agua. Faja de 8cm.    Elastico de 0,5 cm en la faja. Costuras reforzadas. RECOMENDACION DE TALLES: TALLE 1: 34/36/38 pantalón TALLE 2: 38/40/42 pantalón- REFERENCIA: La modelo de la foto esta usando un TALLE 1. *Las medidas pueden variar en milímetros debido a la confección, tipo de tela y costuras.",
    category: "calzascortas",
    img: "https://res.cloudinary.com/dxzytrwpw/image/upload/v1712944146/IMG_5207_cykm0r.jpg",
  },
  {
    id: 3,
    title: "Calza Corta Morley Verde",
    price: 14000,
    stock: 3,
    description: "Calza corta de Lycra de Morley",
    description2: "Calza corta de Lycra de primera calidad (92% poliester y 8% elastómero).    Estampada mediante sublimacion. Resistente a la exposición al sol, cloro y agua. Faja de 8cm.    Elastico de 0,5 cm en la faja. Costuras reforzadas. RECOMENDACION DE TALLES: TALLE 1: 34/36/38 pantalón TALLE 2: 38/40/42 pantalón- REFERENCIA: La modelo de la foto esta usando un TALLE 1. *Las medidas pueden variar en milímetros debido a la confección, tipo de tela y costuras.",
    category: "calzascortas",
    img: "https://res.cloudinary.com/dxzytrwpw/image/upload/v1712944150/IMG_5399_tba0pg.jpg",
  },
  {
    id: 4,
    title: "Calza Larga Aura",
    price: 19900,
    stock: 3,
    description: "Calza larga de Lycra, sublimada",
    description2:
      "Calza larga de Lycra de primera calidad (92% poliester y 8% elastómero).    Estampada mediante sublimacion. Resistente a la exposición al sol, cloro y agua. Faja de 8cm.    Elastico de 0,5 cm en la faja. Costuras reforzadas. RECOMENDACION DE TALLES: TALLE 1: 34/36/38 pantalón TALLE 2: 38/40/42 pantalón- REFERENCIA: La modelo de la foto esta usando un TALLE 1. *Las medidas pueden variar en milímetros debido a la confección, tipo de tela y costuras.",
    category: "calzaslargas",
    img: "https://res.cloudinary.com/dxzytrwpw/image/upload/v1712944143/IMG_5086_kmp9bx.jpg",
  },
  {
    id: 5,
    title: "Calza Larga Camila",
    price: 19900,
    stock: 3,
    description: "Calza larga de Lycra, sublimada",
    description2:
      "Calza larga de Lycra de primera calidad (92% poliester y 8% elastómero).    Estampada mediante sublimacion. Resistente a la exposición al sol, cloro y agua. Faja de 8cm.    Elastico de 0,5 cm en la faja. Costuras reforzadas. RECOMENDACION DE TALLES: TALLE 1: 34/36/38 pantalón TALLE 2: 38/40/42 pantalón- REFERENCIA: La modelo de la foto esta usando un TALLE 1. *Las medidas pueden variar en milímetros debido a la confección, tipo de tela y costuras.",
    category: "calzaslargas",
    img: "https://res.cloudinary.com/dxzytrwpw/image/upload/v1712944147/IMG_5231_cgjasu.jpg",
  },
  {
    id: 6,
    title: "Calza Larga Morley Verde",
    price: 19900,
    stock: 3,
    description: "Calza larga de Lycra de Morley",
    description2:
      "Calza larga de Lycra de primera calidad (92% poliester y 8% elastómero).    Estampada mediante sublimacion. Resistente a la exposición al sol, cloro y agua. Faja de 8cm.    Elastico de 0,5 cm en la faja. Costuras reforzadas. RECOMENDACION DE TALLES: TALLE 1: 34/36/38 pantalón TALLE 2: 38/40/42 pantalón- REFERENCIA: La modelo de la foto esta usando un TALLE 1. *Las medidas pueden variar en milímetros debido a la confección, tipo de tela y costuras.",
    category: "calzaslargas",
    img: "https://res.cloudinary.com/dxzytrwpw/image/upload/v1712944150/IMG_5351_mteaqr.jpg",
  },
  {
    id: 7,
    title: "Top Gala",
    price: 12000,
    stock: 3,
    description: "Top deportivo de Lycra, sublimado",
    description2:
      "Top de tiritas de Lycra de primera calidad (92% poliester y 8% elastómero). Estampada mediante sublimacion. Resistente a la exposición al sol, cloro y agua. Elastico de 3 cm bajo busto. Delantera forrada, con espacio para agregar tazas. Costuras reforzadas.    REFERENCIA: La modelo de la foto esta usando un TALLE 1.                                      *Las medidas pueden variar en milímetros debido a la confección, tipo de tela y costuras.",
    category: "tops",
    img: "https://res.cloudinary.com/dxzytrwpw/image/upload/v1712944145/IMG_4723_aoho2z.jpg",
  },
  {
    id: 8,
    title: "Top Amelie",
    price: 12000,
    stock: 3,
    description: "Top deportivo de Lycra, sublimado",
    description2:
      "Top de tiritas de Lycra de primera calidad (92% poliester y 8% elastómero). Estampada mediante sublimacion. Resistente a la exposición al sol, cloro y agua. Elastico de 3 cm bajo busto. Delantera forrada, con espacio para agregar tazas. Costuras reforzadas.    REFERENCIA: La modelo de la foto esta usando un TALLE 1.                                      *Las medidas pueden variar en milímetros debido a la confección, tipo de tela y costuras.",
    category: "tops",
    img: "https://res.cloudinary.com/dxzytrwpw/image/upload/v1712944145/IMG_4912_gnicmx.jpg",
  },
  {
    id: 9,
    title: "Top Morley Negro",
    price: 12000,
    stock: 3,
    description: "Top deportivo de Lycra de Morley",
    description2:
      "Top de tiritas de Lycra de primera calidad (92% poliester y 8% elastómero). Estampada mediante sublimacion. Resistente a la exposición al sol, cloro y agua. Elastico de 3 cm bajo busto. Delantera forrada, con espacio para agregar tazas. Costuras reforzadas.    REFERENCIA: La modelo de la foto esta usando un TALLE 1.                                      *Las medidas pueden variar en milímetros debido a la confección, tipo de tela y costuras.",
    category: "tops",
    img: "https://res.cloudinary.com/dxzytrwpw/image/upload/v1712944145/IMG_4961_cfifz0.jpg",
  },
];
